### Heroes Of Pymoli Data Analysis
* Of the 1163 active players, the vast majority are male (84%). There also exists, a smaller, but notable proportion of female players (14%).

* Our peak age demographic falls between 20-24 (44.8%) with secondary groups falling between 15-19 (18.60%) and 25-29 (13.4%).  
-----

### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import pandas as pd
import numpy as np

# File to Load (Remember to Change These)
file_to_load = "Resources/purchase_data.csv"

# Read Purchasing File and store into Pandas data frame
purchase_data = pd.read_csv(file_to_load)
#purchase_data.dtypes

## Player Count

* Display the total number of players

In [325]:
total_players = len(purchase_data["SN"].unique())
total_players_df = pd.DataFrame({"Total Player" : [ total_players ] })
total_players_df

   Total Player
0           576

## Purchasing Analysis (Total)

* Run basic calculations to obtain number of unique items, average price, etc.


* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [326]:
total_unique = len(purchase_data["Item ID"].unique())
avg_price = purchase_data["Price"].mean()
total_rev = purchase_data["Price"].sum()
total_purchase = purchase_data["Item ID"].count()
summary_df = pd.DataFrame({"Number of Unique Items": [total_unique],
                              "Average Purchase Price": [avg_price],
                              "Total Number of Purchases": [total_purchase],
                              "Total Revenue": [total_rev]})
summary_df.index = [''] * len(summary_df)
summary_df

,Number of Unique Items,Average Purchase Price,Total Number of Purchases,Total Revenue
,183,3.050987,780,2379.77

## Gender Demographics

* Percentage and Count of Male Players


* Percentage and Count of Female Players


* Percentage and Count of Other / Non-Disclosed

In [327]:
male_data = purchase_data.loc[purchase_data["Gender"] == "Male", : ]
other_data = purchase_data.loc[purchase_data["Gender"] == "Other / Non-Disclosed", : ]
female_data = purchase_data.loc[purchase_data["Gender"] == "Female", : ]
male_count = len(male_data["SN"].unique())
other_count = len(other_data["SN"].unique())
female_count = len(female_data["SN"].unique())
gender_count = male_count + female_count + other_count
gender_dfx = pd.DataFrame({"Male Count": [male_count],
                             "Male Percent": [str(round(male_count * 100 / gender_count, 2)) + "%"],
                            "Female Count": [female_count],
                             "Female Percent": [str(round(female_count * 100 / gender_count, 2)) + '%'],
                             "Other Gender count": [other_count],
                             "Other Percent": [str(round(other_count * 100 / gender_count, 2)) + '%'],
                            })
gender_df = pd.DataFrame({"":          ["Male", "Female", "Other / Non-Disclose"],
                        "Total Count": [male_count, female_count, other_count ],
                        "Percentage of Players": [str(round(male_count * 100 / gender_count, 2)) + "%",
                                                  str(round(female_count * 100 / gender_count, 2)) + '%',
                                                  str(round(other_count * 100 / gender_count, 2)) + '%'],
                            })
gender_df.index = [''] * len(gender_df)
gender_df

                        Total Count Percentage of Players
                  Male          484                84.03%
                Female           81                14.06%
  Other / Non-Disclose           11                 1.91%


## Purchasing Analysis (Gender)

* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. by gender




* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [328]:
purchase_count = [len(male_data["Purchase ID"]), len(female_data["Purchase ID"]), len(other_data["Purchase ID"]) ]
total_price = [male_data["Price"].sum(), female_data["Price"].sum(), other_data["Price"].sum()]

average_price = [ round(total_price[j]/purchase_count[k], 2) for j in range(len(total_price)) \
                 for k in range(len(purchase_count)) if j == k ] 

average_purchase_per_person = [ round(total_price[0] / len(male_data["SN"].unique()),2),
                                round(total_price[1] / len(female_data["SN"].unique()),2),
                                round(total_price[2] / len(other_data["SN"].unique()),2) ]

Purchasing_Analysis_df = pd.DataFrame({"Gender": ["male", "female", "Other / Non-Disclosed"],
                            "Purchase Count": purchase_count,
                            "Average Purchase Price": average_price,
                            "Total Purchase Value": total_price,
                            "Average Purchase Total per Person ": average_purchase_per_person,
                            })
Purchasing_Analysis_df.index = [''] * len(Purchasing_Analysis_df)
Purchasing_Analysis_df

,Gender,Purchase Count,Average Purchase Price,Total Purchase Value,Average Purchase Total per Person
,male,652,3.02,1967.64,4.07
,female,113,3.20,361.94,4.47
,Other / Non-Disclosed,15,3.35,50.19,4.56

## Age Demographics

* Establish bins for ages


* Categorize the existing players using the age bins. Hint: use pd.cut()


* Calculate the numbers and percentages by age group


* Create a summary data frame to hold the results


* Optional: round the percentage column to two decimal points


* Display Age Demographics Table

In [329]:
age_less_10_data = purchase_data.loc[(purchase_data["Age"] < 10), :]
age_10_14_data = purchase_data.loc[(purchase_data["Age"] >= 10) & (purchase_data["Age"] < 15), :]
age_15_19_data = purchase_data.loc[(purchase_data["Age"] >= 15) & (purchase_data["Age"] < 20), :]
age_20_24_data = purchase_data.loc[(purchase_data["Age"] >= 20) & (purchase_data["Age"] < 25), :]
age_25_29_data = purchase_data.loc[(purchase_data["Age"] >= 25) & (purchase_data["Age"] < 30), :]
age_30_34_data = purchase_data.loc[(purchase_data["Age"] >= 30) & (purchase_data["Age"] < 35), :]
age_35_39_data = purchase_data.loc[(purchase_data["Age"] >= 35) & (purchase_data["Age"] < 40), :]
age_over_40_data = purchase_data.loc[(purchase_data["Age"] >= 40 ), :]
#purchase_data.head()
#purchase_data["Age Group"] = pd.cut(purchase_data.Age,[0, 9,15,19,24,29,34,39])
age = ["<10", "10-14", "15-19", "20-24", "25-29", "30-34", "35-39", "40+"]
# 
# purchase_data["Age Group"] = pd.cut(purchase_data.Age,[0, 9,15,19,24,29,34,39])
#initialize
total_count = []
total_player_count = 0
for data in (age_less_10_data, age_10_14_data, age_15_19_data, age_20_24_data,
             age_25_29_data, age_30_34_data, age_35_39_data, age_over_40_data):
    age_group_cnt = len(data["SN"].unique())
    total_count.append(age_group_cnt)
    total_player_count += age_group_cnt
Percent_player = [ str(round(i * 100 /total_player_count, 2))+"%" for i in total_count]
age_demo_df = pd.DataFrame({
    "":age, "Total Count":total_count, "Percentage of Players":Percent_player })
age_demo_df.index = [''] * len(age_demo_df)
age_demo_df

         Total Count Percentage of Players
    <10           17                 2.95%
  10-14           22                 3.82%
  15-19          107                18.58%
  20-24          258                44.79%
  25-29           77                13.37%
  30-34           52                 9.03%
  35-39           31                 5.38%
    40+           12                 2.08%

## Purchasing Analysis (Age)

* Bin the purchase_data data frame by age


* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. in the table below


* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [330]:

#initialize 
purchase_count = []
total_price = []
average_price = [] 
average_purchase_per_person = []
for data in ( age_less_10_data, age_10_14_data, age_15_19_data, age_20_24_data,
              age_25_29_data, age_30_34_data, age_35_39_data, age_over_40_data):
    purchase_cnt = len(data["Purchase ID"])
    purchase_count.append(purchase_cnt)
    
    tot_price = data["Price"].sum()
    total_price.append(tot_price)
    
    avg_price = "N/A" if purchase_cnt <= 0 else str(round(tot_price/purchase_cnt,2)) 
    average_price.append(avg_price)
    
    avg_purchase_per_person = "N/A" if len(data["SN"].unique()) <= 0 else  \
    str(round(tot_price / len(data["SN"].unique()),2))
    average_purchase_per_person.append(avg_purchase_per_person)
    
Purchase_analysis_df = pd.DataFrame({"Age":age, "Purchase Count":purchase_count, 
                                     "Average Purchase Price":average_price,
                                     "Total Purchase Value":total_price, 
                               "Average Purchase Total per Person by Age Group":average_purchase_per_person
                                    })

Purchase_analysis_df

,Age,Purchase Count,Average Purchase Price,Total Purchase Value,Average Purchase Total per Person by Age Group
0,<10,23,3.35,77.13,4.54
1,10-14,28,2.96,82.78,3.76
2,15-19,136,3.04,412.89,3.86
3,20-24,365,3.05,1114.06,4.32
4,25-29,101,2.9,293.00,3.81
5,30-34,73,2.93,214.00,4.12
6,35-39,41,3.6,147.67,4.76
7,40+,13,2.94,38.24,3.19

## Top Spenders

* Run basic calculations to obtain the results in the table below


* Create a summary data frame to hold the results


* Sort the total purchase value column in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the summary data frame

In [331]:
sum_df = purchase_data.groupby(['SN'], sort=True).sum()
sum_df.rename(columns={'Price':'Total Purchase Value'}, inplace=True)
count_df = purchase_data.groupby(['SN'], sort=True).count()
count_df.rename(columns={'Price':'Purchase Count'}, inplace=True)
result_df = pd.concat([count_df.loc[ : , ['Purchase Count'] ], sum_df.loc[ : , ['Total Purchase Value'] ] ], axis=1, sort=False)
result_df = result_df.sort_values(by = ['Total Purchase Value'], ascending=[False]) 
result_df['Average Purchase Price'] = result_df['Total Purchase Value'].divide(result_df['Purchase Count']).round(2)
print(result_df.loc[:,["Purchase Count", "Average Purchase Price", "Total Purchase Value"]].head())

             Purchase Count  Average Purchase Price  Total Purchase Value
SN
Lisosia93                 5                    3.79                 18.96
Idastidru52               4                    3.86                 15.45
Chamjask73                3                    4.61                 13.83
Iral74                    4                    3.40                 13.62
Iskadarya95               3                    4.37                 13.10

## Most Popular Items

* Retrieve the Item ID, Item Name, and Item Price columns


* Group by Item ID and Item Name. Perform calculations to obtain purchase count, item price, and total purchase value


* Create a summary data frame to hold the results


* Sort the purchase count column in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the summary data frame

In [332]:
shorted_df = purchase_data.loc[ :, [ 'Item ID', 'Item Name', 'Price']]
count_df = shorted_df.groupby(['Item ID', 'Item Name']).agg({
     'Price': ['count', 'mean', 'sum']
   })
count_df = count_df.sort_values(('Price', 'count'), ascending=[False])
count_df.rename(columns={'Price':'',
                        'count':'Purchase Count',
                        'mean': 'Item Price',
                         'sum':'Total Purchase Value'}, inplace=True)
count_df.head()
list(count_df.columns)

[('', 'Purchase Count'), ('', 'Item Price'), ('', 'Total Purchase Value')]

## Most Profitable Items

* Sort the above table by total purchase value in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the data frame

In [333]:
count_df = count_df.sort_values(('', 'Total Purchase Value'), ascending=[False])
count_df

                                                                     \
                                                     Purchase Count
Item ID Item Name
178     Oathbreaker, Last Hope of the Breaking Storm             12
82      Nirvana                                                   9
145     Fiery Glass Crusader                                      9
92      Final Critic                                              8
103     Singed Scalpel                                            8
59      Lightning, Etcher of the King                             8
108     Extraction, Quickblade Of Trembling Hands                 9
78      Glimmer, Ender of the Moon                                7
72      Winter's Bite                                             8
60      Wolf                                                      8
179     Wolf, Promise of the Moonwalker                           6
160     Azurewrath                                                6
25      Hero Cane                                                 6
37      Shadow Strike, Glory of Ending Hope                       8
139     Mercy, Katana of Dismay                                   5
128     Blazeguard, Reach of Eternity                             5
138     Peacekeeper, Wit of Dark Magic                            5
141     Persuasion                                                7
87      Deluge, Edge of the West                                  5
159     Oathbreaker, Spellblade of Trials                         7
136     Ghastly Adamantite Protector                              6
65      Conqueror Adamantite Mace                                 5
101     Final Critic                                              5
102     Avenger                                                   6
133     Faith's Scimitar                                          5
39      Betrayal, Whisper of Grieving Widows                      5
111     Misery's End                                              4
165     Bone Crushing Silver Skewer                               4
52      Hatred                                                    4
75      Brutality Ivory Warmace                                   8
...                                                             ...
124     Venom Claymore                                            4
0       Splinter                                                  4
155     War-Forged Gold Deflector                                 5
48      Rage, Legacy of the Lone Victor                           2
158     Darkheart, Butcher of the Champion                        2
51      Endbringer                                                1
134     Undead Crusader                                           1
30      Stormcaller                                               2
135     Warped Diamond Crusader                                   3
91      Celeste                                                   1
177     Winterthorn, Defender of Shifting Worlds                  2
70      Hope's End                                                4
115     Spectral Diamond Doomblade                                2
69      Frenzy, Defender of the Harvest                           2
47      Alpha, Reach of Ending Hope                               1
180     Stormcaller                                               1
27      Riddle, Tribute of Ended Dreams                           1
183     Dragon's Greatsword                                       3
31      Trickster                                                 2
168     Sun Strike, Jaws of Twisted Visions                       2
90      Betrayer                                                  1
33      Curved Axe                                                2
26      Unholy Wand                                               2
118     Ghost Reaver, Longsword of Magic                          1
28      Flux, Destroyer of Due Diligence                          2
125     Whistling Mithril Warblade                                2
126     Exiled Mithril Longsword                                  1
23      Crucifer                                                  1
104     Gladiator's Glaive                                        1
42      The Decapitator                                           1

                                                                 \
                                                     Item Price
Item ID Item Name
178     Oathbreaker, Last Hope of the Breaking Storm       4.23
82      Nirvana                                            4.90
145     Fiery Glass Crusader                               4.58
92      Final Critic                                       4.88
103     Singed Scalpel                                     4.35
59      Lightning, Etcher of the King                      4.23
108     Extraction, Quickblade Of Trembling Hands          3.53
78      Glimmer, Ender of the Moon                         4.40
72      Winter's Bite                                      3.77
60      Wolf                                               3.54
179     Wolf, Promise of the Moonwalker                    4.48
160     Azurewrath                                         4.40
25      Hero Cane                                          4.35
37      Shadow Strike, Glory of Ending Hope                3.16
139     Mercy, Katana of Dismay                            4.94
128     Blazeguard, Reach of Eternity                      4.91
138     Peacekeeper, Wit of Dark Magic                     4.74
141     Persuasion                                         3.19
87      Deluge, Edge of the West                           4.43
159     Oathbreaker, Spellblade of Trials                  3.08
136     Ghastly Adamantite Protector                       3.58
65      Conqueror Adamantite Mace                          4.24
101     Final Critic                                       4.19
102     Avenger                                            3.44
133     Faith's Scimitar                                   4.09
39      Betrayal, Whisper of Grieving Widows               3.94
111     Misery's End                                       4.89
165     Bone Crushing Silver Skewer                        4.86
52      Hatred                                             4.84
75      Brutality Ivory Warmace                            2.42
...                                                         ...
124     Venom Claymore                                     1.29
0       Splinter                                           1.28
155     War-Forged Gold Deflector                          1.01
48      Rage, Legacy of the Lone Victor                    2.48
158     Darkheart, Butcher of the Champion                 2.45
51      Endbringer                                         4.66
134     Undead Crusader                                    4.50
30      Stormcaller                                        2.21
135     Warped Diamond Crusader                            1.40
91      Celeste                                            4.17
177     Winterthorn, Defender of Shifting Worlds           2.08
70      Hope's End                                         1.03
115     Spectral Diamond Doomblade                         2.04
69      Frenzy, Defender of the Harvest                    1.98
47      Alpha, Reach of Ending Hope                        3.58
180     Stormcaller                                        3.36
27      Riddle, Tribute of Ended Dreams                    3.30
183     Dragon's Greatsword                                1.09
31      Trickster                                          1.55
168     Sun Strike, Jaws of Twisted Visions                1.48
90      Betrayer                                           2.94
33      Curved Axe                                         1.16
26      Unholy Wand                                        1.12
118     Ghost Reaver, Longsword of Magic                   2.17
28      Flux, Destroyer of Due Diligence                   1.06
125     Whistling Mithril Warblade                         1.00
126     Exiled Mithril Longsword                           2.00
23      Crucifer                                           1.99
104     Gladiator's Glaive                                 1.93
42      The Decapitator                                    1.75


                                                     Total Purchase Value
Item ID Item Name
178     Oathbreaker, Last Hope of the Breaking Storm                50.76
82      Nirvana                                                     44.10
145     Fiery Glass Crusader                                        41.22
92      Final Critic                                                39.04
103     Singed Scalpel                                              34.80
59      Lightning, Etcher of the King                               33.84
108     Extraction, Quickblade Of Trembling Hands                   31.77
78      Glimmer, Ender of the Moon                                  30.80
72      Winter's Bite                                               30.16
60      Wolf                                                        28.32
179     Wolf, Promise of the Moonwalker                             26.88
160     Azurewrath                                                  26.40
25      Hero Cane                                                   26.10
37      Shadow Strike, Glory of Ending Hope                         25.28
139     Mercy, Katana of Dismay                                     24.70
128     Blazeguard, Reach of Eternity                               24.55
138     Peacekeeper, Wit of Dark Magic                              23.70
141     Persuasion                                                  22.33
87      Deluge, Edge of the West                                    22.15
159     Oathbreaker, Spellblade of Trials                           21.56
136     Ghastly Adamantite Protector                                21.48
65      Conqueror Adamantite Mace                                   21.20
101     Final Critic                                                20.95
102     Avenger                                                     20.64
133     Faith's Scimitar                                            20.45
39      Betrayal, Whisper of Grieving Widows                        19.70
111     Misery's End                                                19.56
165     Bone Crushing Silver Skewer                                 19.44
52      Hatred                                                      19.36
75      Brutality Ivory Warmace                                     19.36
...                                                                   ...
124     Venom Claymore                                               5.16
0       Splinter                                                     5.12
155     War-Forged Gold Deflector                                    5.05
48      Rage, Legacy of the Lone Victor                              4.96
158     Darkheart, Butcher of the Champion                           4.90
51      Endbringer                                                   4.66
134     Undead Crusader                                              4.50
30      Stormcaller                                                  4.42
135     Warped Diamond Crusader                                      4.20
91      Celeste                                                      4.17
177     Winterthorn, Defender of Shifting Worlds                     4.16
70      Hope's End                                                   4.12
115     Spectral Diamond Doomblade                                   4.08
69      Frenzy, Defender of the Harvest                              3.96
47      Alpha, Reach of Ending Hope                                  3.58
180     Stormcaller                                                  3.36
27      Riddle, Tribute of Ended Dreams                              3.30
183     Dragon's Greatsword                                          3.27
31      Trickster                                                    3.10
168     Sun Strike, Jaws of Twisted Visions                          2.96
90      Betrayer                                                     2.94
33      Curved Axe                                                   2.32
26      Unholy Wand                                                  2.24
118     Ghost Reaver, Longsword of Magic                             2.17
28      Flux, Destroyer of Due Diligence                             2.12
125     Whistling Mithril Warblade                                   2.00
126     Exiled Mithril Longsword                                     2.00
23      Crucifer                                                     1.99
104     Gladiator's Glaive                                           1.93
42      The Decapitator                                              1.75

[183 rows x 3 columns]